# netlify.toml
[build]
  command = "npm ci && npm run build"
  publish = "dist/cameron-profile/browser"

# SPA redirect (Angular routes -> index.html)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
